#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Nov 16 22:01:57 CST 2018
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_3 axi_vip_v1_1_3 zynq_ultra_ps_e_vip_v1_0_3 lib_pkg_v1_0_2 axi_apb_bridge_v3_0_14 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 xlconstant_v1_1_5 generic_baseblocks_v2_1_0 fifo_generator_v13_2_2 axi_data_fifo_v2_1_16 axi_register_slice_v2_1_17 axi_protocol_converter_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim/design_1_zynq_ultra_ps_e_0_1_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_apb_bridge_v3_0_14 $vhdlan_opts \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/2f3b/hdl/axi_apb_bridge_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_apb_bridge_0_0/sim/design_1_axi_apb_bridge_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/CKLNQD12.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/HLS_cdp_icvt.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/HLS_cdp_ocvt.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/MUX2D4.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/MUX2HDD2.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_BLKBOX_SINK.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_BLKBOX_SRC0.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_CLK_gate_power.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CACC_CALC_int8.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CACC_assembly_buffer.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CACC_assembly_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CACC_calculator.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CACC_delivery_buffer.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CACC_delivery_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CACC_dual_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CACC_regfile.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CACC_single_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CACC_slcg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_CVT_cell.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_DC_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_IMG_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_IMG_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_IMG_pack.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_IMG_sg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_IMG_sg2pack_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_WT_8ATMM_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_WT_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_cvt.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_dc.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_dma_mux.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_dual_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_img.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_regfile.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_shared_buffer.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_single_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_slcg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_status.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDMA_wt.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_INTP_unit.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_LUT_CTRL_unit.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_LUT_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_MUL_unit.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_bufferin_tp1.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_cvtin.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_cvtout.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_data_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_intp.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_intpinfo_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_lut.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_mul.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_nan.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_sum.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_sumpd_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_DP_syncfifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_RDMA_REG_dual.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_RDMA_REG_single.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_RDMA_cq.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_RDMA_eg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_RDMA_ig.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_RDMA_lat_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_RDMA_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_RDMA_ro_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_REG_dual.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_REG_single.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_WDMA_dat_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_dp.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_rdma.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_slcg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CDP_wdma.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CFGROM_rom.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CMAC_CORE_active.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CMAC_CORE_cfg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CMAC_CORE_mac.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CMAC_CORE_rt_in.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CMAC_CORE_rt_out.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CMAC_CORE_slcg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CMAC_REG_dual.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CMAC_REG_single.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CMAC_core.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CMAC_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CSB_MASTER_csb2falcon_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CSB_MASTER_falcon2csb_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CSC_SG_dat_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CSC_SG_wt_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CSC_WL_dec.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CSC_dl.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CSC_dual_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CSC_regfile.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CSC_sg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CSC_single_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CSC_slcg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_CSC_wl.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_DMAIF_rdreq.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_DMAIF_rdrsp.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_DMAIF_wr.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_GLB_CSB_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_GLB_csb.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_GLB_ic.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_HLS_saturate.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_HLS_shiftleftsu.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_HLS_shiftrightsatsu.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_HLS_shiftrightsu.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_CSB_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_READ_IG_arb.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_READ_IG_bpt.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_READ_IG_cvt.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_READ_eg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_READ_ig.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_WRITE_IG_arb.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_WRITE_IG_bpt.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_WRITE_IG_cvt.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_WRITE_cq.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_WRITE_eg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_WRITE_ig.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_csb.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_read.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_MCIF_write.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_CORE_cal1d.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_CORE_cal2d.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_CORE_preproc.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_CORE_unit1d.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_RDMA_REG_dual.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_RDMA_REG_single.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_RDMA_cq.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_RDMA_eg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_RDMA_ig.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_RDMA_lat_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_RDMA_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_RDMA_ro_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_REG_dual.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_REG_single.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_WDMA_DAT_fifo.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_WDMA_cmd.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_WDMA_dat.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_core.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_nan.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_rdma.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_slcg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_PDP_wdma.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_BRDMA_cq_lib.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_BRDMA_gate.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_BRDMA_lat_fifo_lib.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_CORE_gate.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_CORE_pack.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_CORE_unpack.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_HLS_C_int.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_HLS_X_int_alu.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_HLS_X_int_mul.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_HLS_X_int_relu.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_HLS_X_int_trt.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_HLS_c.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_HLS_prelu.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_HLS_relu.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_HLS_sync2data.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_HLS_x1_int.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_HLS_x2_int.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_MRDMA_EG_cmd.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_MRDMA_EG_din.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_MRDMA_EG_dout.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_MRDMA_EG_lat_fifo_lib.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_MRDMA_cq_lib.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_MRDMA_eg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_MRDMA_gate.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_MRDMA_ig.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_NRDMA_cq_lib.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_NRDMA_gate.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_NRDMA_lat_fifo_lib.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_RDMA_EG_ro.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_RDMA_REG_dual.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_RDMA_REG_single.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_RDMA_dmaif.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_RDMA_eg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_RDMA_ig.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_RDMA_pack.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_RDMA_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_RDMA_unpack.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_REG_dual.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_REG_single.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_WDMA_DAT_in.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_WDMA_DAT_out.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_WDMA_cmd.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_WDMA_dat.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_WDMA_gate.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_WDMA_intr.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_brdma.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_cmux.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_core.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_mrdma.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_nrdma.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_rdma.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_reg.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_SDP_wdma.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_XXIF_libs.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_apb2csb.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_cacc.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_cbuf.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_cdma.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_cdp.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_cfgrom.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_cmac.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_core_reset.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_csb_master.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_csc.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_glb.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_mcif.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_partition_a.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_partition_c.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_partition_m.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_partition_o.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_partition_p.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_pdp.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_reset.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_sdp.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_sync3d.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_sync3d_c.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_NVDLA_sync3d_s.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/NV_nvdla.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/OR2D1.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/int_sum_block_tp1.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rws_128x18.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rws_16x256.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rws_16x272.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rws_16x64.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rws_256x3.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rws_256x64.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rwsp_128x11.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rwsp_128x6.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rwsp_16x14.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rwsp_16x16.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rwsp_16x65.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rwsp_8x65.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rwst_256x8.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rwsthp_20x4.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rwsthp_60x21.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rwsthp_80x17.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/nv_ram_rwsthp_80x9.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/oneHotClk_async_read_clock.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/oneHotClk_async_write_clock.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/p_SSYNC2DO_C_PP.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/p_SSYNC3DO.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/p_SSYNC3DO_C_PPP.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/p_SSYNC3DO_S_PPP.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/p_STRICTSYNC3DOTM_C_PPP.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/sync3d.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/sync3d_c_ppp.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/sync3d_s_ppp.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/src/sync_reset.v" \
    "$ref_dir/../../../bd/design_1/ipshared/77a6/hdl/nvdla_v1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_nvdla_0_0/sim/design_1_nvdla_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_vcu_0_0/sim/design_1_proc_sys_reset_vcu_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5160/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_48ac_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/acc2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_48ac_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/28cb/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_48ac_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_48ac_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_48ac_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_48ac_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_48ac_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_48ac_m00bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_48ac_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_48ac_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_48ac_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_48ac_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_48ac_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/afa8/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_48ac_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/4521/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_48ac_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/d1fc/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_48ac_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/4e7b/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_48ac_arsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_48ac_rsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_48ac_awsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_48ac_wsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_48ac_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_48ac_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_48ac_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/sim/bd_48ac.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/sim/design_1_smartconnect_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../bd/design_1/ipshared/77a6/src" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-nvdla.srcs/sources_1/bd/design_1/ipshared/77a6/src" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/geralt/nvdla/Zynq-nvdla/zynq-nvdla/zynq-nvdla.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
